### ISSUE TITLE
Option"s" object - small typo

### ISSUE THREAD

**Issue by s-oehding** [kevinongko/vue-chart-js#1]
Hi, there is a small typo in the createChart method causing the options object not getting passed correctly.

I fixed it here:
https://github.com/s-oehding/vue-chart-js/commit/f2f121a4732b3d5c6ed8eb2a47ea6c36cbc4c5a2

**Comment by kevinongko** [comment]
Hi @s-oehding ,

Thanks for the PR, merged!
