### ISSUE TITLE
not updating after query

### ISSUE THREAD

**Issue by ralpdexterbongato** [kevinongko/vue-chart-js#10]
after i query and put the data to datasets data , i can only see the bars updated after i clicked on the labels. ,is it possible to execute the .update() from my component?

**Comment by kevinongko** [comment]
Hi @ralpdexterbongato,

does issue #7 solve your probelm?

**Comment by ralpdexterbongato** [comment]
yes thank you..

**Comment by kylef000** [comment]
I don't mean to reopen this issue, just wanted to add a note for anyone who comes looking and #7 doesn't solve their issue.

I found that when I was updating fields on a parent component that passed to the child component (of which vue-chart is a child), I needed to include a deep watch on the data() variable that gets passed to datasets. In the watch, I call a method that runs the code in the #7 resolution.

Refer to https://vuejs.org/v2/api/#vm-watch and "Option: deep"
