### ISSUE TITLE
How can I handle click events on the chart °

### ISSUE THREAD

**Issue by bleekbless** [kevinongko/vue-chart-js#3]
I have tryed all ways but none seem to work

**Comment by kevinongko** [comment]
Hi @bleekbless ,

according to chart.js [docs](http://www.chartjs.org/docs/latest/general/interactions/events.html) you can pass `onClick` function as options using the `options` [props](https://github.com/kevinongko/vue-chart-js#props).

**Comment by bleekbless** [comment]
Thanks for the answer
