### ISSUE TITLE
Send dispatch or emit from Chart to parent view

### ISSUE THREAD

**Issue by bleekbless** [kevinongko/vue-chart-js#4]
How can I send some data from the chart to a parente view?

**Comment by kevinongko** [comment]
Hi @bleekbless ,

What kind of data you need to send to parent component?

**Comment by bleekbless** [comment]
Actually I have 2 questions number 1 is I have to send some text information so the parent componentes canal make another request and show some response the other one os that i need to store more than one data per dot in a line chart

**Comment by kevinongko** [comment]
1. What kind of interaction needed to trigger it? IMO the chart should only receive data from parent and show the data, any data changes should be handled by the parent component, if you need to trigger event from the chart, check out the event [docs](http://www.chartjs.org/docs/latest/general/interactions/events.html).
2. I don't quite get what kind of line chart you mean, does it exist in the [sample](http://www.chartjs.org/samples/latest/)?

**Comment by kevinongko** [comment]
Closed because inactivity.
