### ISSUE TITLE
Chart not updating when data changes

### ISSUE THREAD

**Issue by aaronlumsden** [kevinongko/vue-chart-js#7]
When I update the data for the chart, the tooltip on the chart displays the correct data however the chart doesn't. I am using a radar chart.

**Comment by kevinongko** [comment]
Hi @aarondo,

could you show me your sample code in [jsbin](http://jsbin.com/)? thanks

**Comment by aaronlumsden** [comment]
I cant really do that as Im using vueify.

I have this in my template

`<vue-chart type="radar" :data="chartData" :options="chartOptions"></vue-chart>`

Then when I update chartData on an event. It updates the data in the tooltip on the chart but doesnt update the radar chart.

**Comment by kevinongko** [comment]
How do you update your `chartData`?

**Comment by aaronlumsden** [comment]
This is how I update the data
this.$set(this.chartData.datasets[0],'data',[1,2,4,5]); which I can see updating in the chart tooltip.

Do I need to do anything once the data has been updated. i can see in the standard chart js docs. That I would normally need to call chart.update(); once the data has been changed?

**Comment by aaronlumsden** [comment]
I managed to get this working. Rather than just updating the datasets data. I had to update the whole chartdata object like this

```
 this.chartData = {
      labels: ['Plan', 'Reach', 'Act','Convert','Engage'],
      datasets: [{
      borderColor:'#fe5a68',
      pointBackgroundColor: '#fe5a68',
      pointBorderColor: '#fe5a68',
      pointRadius: 4,
      backgroundColor:'rgba(254,90,104,0.5)',
      data: [1, 2, 4,5]
      }]
     }
```

**Comment by kevinongko** [comment]
There are 2 watchers, labels and datasets, to trigger the datasets watcher you need to write it like this:

```js
      this.$set(this.chartData.datasets, 0, {
        data: [50, 40, 90],
        label: 'component 1'
      })
```

**Comment by MirGorog-veeva** [comment]
To me this worked only:
(vue.js , vue-chart.js)
template part:
 <b-select @change="changeData($event)"><b-select>
 <donut-chart ref="firstDonut" :chartdata:"chartdata" :options: "options"><donut-chart>
...
script part: 
methods: {
    changeData(changed) {
       this.selectedProductId = changed
       this.$refs.firstDonut.renderChart(this.chartdata, this.options)
     }
}
Hope I could help
