### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by alziqziq** [kevinongko/vue-chart-js#8]
how to set minimum value??

**Comment by kevinongko** [comment]
@alziqziq what kind of minimum value?

**Comment by alziqziq** [comment]
the left side value always start from minimum value, i want to start from 0.

![image](https://user-images.githubusercontent.com/29282122/30583704-ee711ddc-9d51-11e7-87a6-9e8a1ee5873f.png)

**Comment by engoyan** [comment]
@alziqziq add options attribute. You can find an example here: http://www.chartjs.org/docs/latest/

**Comment by kevinongko** [comment]
As @engoyan said, try adding `beginAtZero: true` in option attribute

**Comment by alziqziq** [comment]
oke thank @engoyan @kevinongko
